# disabled_blocks and number_of_blocks only apply if random_blocks is set to true.
presets:
  ordered:
    world_name: world
    nether_world_name: world_nether
    end_world_name: world_the_end
    worldborder_diameter: 500
    default_game_world_name: world
    spawn_location:
      x: 0
      y: 64
      z: 0
    spawn_radius: 10
    round_time: 30
    elimination: true
    random_blocks: false
    max_number_of_rounds: 10
    random_order: true
    blocks:
      - GRASS_BLOCK
      - STONE
      - COBBLESTONE
  random:
    world_name: world
    nether_world_name: world_nether
    end_world_name: world_the_end
    worldborder_diameter: 500
    default_game_world_name: world
    spawn_location:
      x: 0
      y: 64
      z: 0
    spawn_radius: 10
    round_time: 30
    elimination: true
    random_blocks: true
    max_number_of_rounds: 10
    disabled_blocks:
      - END_CRYSTAL
      - BARRIER
      - COMMAND_BLOCK
