name: BlockHunt
version: 1.0.0
author: MylesMor
main: dev.mylesmor.blockhunt.BlockHunt
api-version: 1.16
depend: [ProtocolLib]
commands:
  blockhunt:
    description: Opens the BlockHunt help menu.
    aliases: [bh]
  check:
    description: Checks the block.
